---
- name: Create Pi-hole project directory
  file:
    path: "{{ pihole_dir }}"
    state: directory

- name: Copy Pi-hole project files
  template:
    src: docker-compose.yaml.j2
    dest: "{{ pihole_dir }}/docker-compose.yaml"
